// AUTO-GENERATED by scripts/extract-dsgai-json.cjs — do not edit manually.
// Source: data/owaspDataSecurity2026.generated.ts
// Regenerate: node scripts/extract-dsgai-json.cjs

export interface DsgaiSummaryItem {
  code: string;
  title: string;
  priority?: 'critical' | 'high' | 'medium' | 'low';
  overview: string;
}

export const DSGAI_SUMMARY: DsgaiSummaryItem[] = [
  {
    "code": "DSPM",
    "title": "DSPM for GenAI (AI-DSPM)",
    "priority": "medium",
    "overview": "AI-DSPM (Data Security Posture Management) for GenAI is the continuous practice of discovering, classifying, governing, and monitoring data across GenAI pipelines and runtimes, so you can see where sensitive data exists, understand how it flows/derives (e.g., into embeddings or logs), and enforce controls that prevent exposure, tampering, and non-compliance."
  },
  {
    "code": "DSGAI01",
    "title": "Sensitive Data Leakage",
    "priority": "critical",
    "overview": "An attacker (or a curious user) interacts with the model or a RAG system that was trained on to retrieve sensitive corporate data. Through carefully crafted instructions, enumeration, or high-recall prompts, the system returns verbatim or near-verbatim sensitive strings (PII/PHI/secrets/IP). Large models can unintentionally restate secrets from training data even without specific user prompting. F"
  },
  {
    "code": "DSGAI02",
    "title": "Agent Identity & Credential Exposure",
    "priority": "critical",
    "overview": "AI agent pipelines generate a rapidly expanding surface of Non-Human Identities (NHIs) -- service accounts, API keys, OAuth tokens, and tool credentials -- that accumulate across orchestration layers with little lifecycle governance. The core vulnerability is one of architectural mismatch: three-legged OAuth flows were designed around human consent, where a user actively delegates a bounded scope "
  },
  {
    "code": "DSGAI03",
    "title": "Shadow AI & Unsanctioned Data Flows",
    "priority": "high",
    "overview": "Business units experiment with public AI SaaS tools, browser plugins, and \"productivity\" agents without security review. Employees paste customer records, internal designs, or source code into these tools. Vendors may retain and train on this data, store it in third-country regions, or expose it via misconfigurations. No formal lineage, DSR handling, or contractual guarantees exist. Shadow AI enco"
  },
  {
    "code": "DSGAI04",
    "title": "Data, Model & Artifact Poisoning",
    "priority": "critical",
    "overview": "The full attack lifecycle moves through three stages that are operationally distinct but technically continuous. Understanding them separately is useful for detection; treating them as separate risks is not. Stage 1 -- Supply chain compromise: AI stacks ingest datasets, pre-trained models, packages, and tools from external sources with varying levels of trust verification. An adversary who control"
  },
  {
    "code": "DSGAI05",
    "title": "Data Integrity & Validation Failures",
    "priority": "high",
    "overview": "AI pipelines ingest data from a wide range of sources -- uploaded files, API feeds, snapshot imports, labeling queues, and third-party data connectors -- and the validation applied at each ingestion boundary is frequently insufficient to catch payloads that are structurally valid but semantically malicious or deliberately crafted to exploit the import mechanism itself. This creates two related but"
  },
  {
    "code": "DSGAI06",
    "title": "Tool, Plugin & Agent Data Exchange Risks",
    "priority": "critical",
    "overview": "Every tool invocation, plugin call, or agent handoff is a potential exfiltration boundary. When an AI assistant calls a plugin, forwards a task to a sub-agent, or receives instructions from an orchestrator, it typically shares all or part of the active conversation context -- including secrets, internal URLs, credentials, PII, and attachments -- with the receiving endpoint. If that endpoint is mal"
  },
  {
    "code": "DSGAI07",
    "title": "Data Governance, Lifecycle & Classification for AI Systems",
    "priority": "high",
    "overview": "In conventional data systems, a governance failure -- missing classification label, expired retention policy, absent lineage record -- is contained to the layer where it occurs. In AI pipelines, the same failure propagates forward and embeds itself in derived artifacts that outlive the source data, are difficult to enumerate, and are in many cases technically irreversible. This propagation dynamic"
  },
  {
    "code": "DSGAI08",
    "title": "Non-Compliance & Regulatory Violations",
    "priority": "medium",
    "overview": "Regulatory exposure in AI systems rarely originates as a discrete event -- it surfaces when technical risks documented elsewhere in this framework go unmitigated and intersect with enforceable legal obligations. Three failure patterns are worth distinguishing, as each triggers different regulatory mechanisms. The first is unlawful basis and consent failure: training data collected without a docume"
  },
  {
    "code": "DSGAI09",
    "title": "Multimodal Capture & Cross-Channel Data Leakage",
    "priority": "high",
    "overview": "Users upload screenshots of dashboards, photos of whiteboards, scans of passports, PDFs, and voice notes so multimodal assistants can \"understand context.\" These files are processed and retained in object stores, embeddings, and logs. The extracted text is as sensitive as the image itself. When images are OCR'd or audio transcribed, the resulting text must carry the same classification as the orig"
  },
  {
    "code": "DSGAI10",
    "title": "Synthetic Data, Anonymization & Transformation Pitfalls",
    "priority": "medium",
    "overview": "The core failure is an assumption that data transformation -- de-identification, tokenization, normalization, or synthetic generation -- produces a privacy guarantee it does not actually provide. This manifests across the data pipeline in three related ways. The first is anonymization and de-identification reversal: quasi-identifiers that survive transformation (age bands, ZIP codes, rare diagnosi"
  },
  {
    "code": "DSGAI11",
    "title": "Cross-Context & Multi-User Conversation Bleed",
    "priority": "critical",
    "overview": "LLM systems reuse conversation state or shared memory across sessions, tenants, or users to create \"persistent assistants.\" Weak isolation between workspaces, mishandled conversation IDs, or bugs in session management cause content from one user/tenant to appear in another's context window or RAG index. We saw this in March 2023 where a ChatGPT bug exposed users' conversation titles to others due "
  },
  {
    "code": "DSGAI12",
    "title": "Unsafe Natural-Language Data Gateways (LLM- to-SQL/Graph)",
    "priority": "high",
    "overview": "Organizations expose data warehouses, graphs, and analytics engines via \"Ask your data\" copilots. The LLM is allowed to generate raw SQL/GraphQL/REST queries over wide schemas. Prompt injection, hallucinated queries, or mis-specified policies lead to overly broad SELECTs, joins that cross tenants, or leaking sensitive columns. Weak validation means the generated queries execute as-is with elevated"
  },
  {
    "code": "DSGAI13",
    "title": "Vector Store Platform Data Security",
    "priority": "critical",
    "overview": "Unencrypted embeddings and permissive vector APIs allow similarity queries to surface sensitive content. Misconfigured and permissive vector APIs, unencrypted data at rest, or long-lived credentials allow unauthorized users to access and exfiltrate the raw embeddings and related metadata. Platform-level flaws (path traversal / arbitrary upload) can escalate to data theft or RCE, compromising entir"
  },
  {
    "code": "DSGAI14",
    "title": "Excessive Telemetry & Monitoring Leakage",
    "priority": "medium",
    "overview": "Teams instrument every request/response with rich logs, traces, and session captures to debug agent workflows and RAG quality. Logging middleware dumps full prompts, tool outputs, vector results, and credentials into centralized observability stacks. Highlight for third-party risk, if using external log analytic services, ensure they are secured to the same standard. Even limited data in logs can "
  },
  {
    "code": "DSGAI15",
    "title": "Over-Broad Context Windows & Prompt Over- Sharing",
    "priority": "high",
    "overview": "To \"improve answers,\" teams pack prompts with full user profiles, tickets, transaction histories, and document blobs. LLM gateways automatically append rich context (e.g., \"customer_360\") to every request. These payloads are sent to external API providers, cached by edge services, and logged for debugging. A breach at the provider, misconfigured cache, or insider with log access now has a 360� vie"
  },
  {
    "code": "DSGAI16",
    "title": "Endpoint & Browser Assistant Overreach",
    "priority": "high",
    "overview": "Users install AI browser extensions and OS/IDE copilots that promise productivity boosts. These tools request broad permissions (\"read and change all your data on websites you visit,\" \"read files in this folder,\" etc.) and stream page content, keystrokes, and code to remote LLM APIs. Malicious or compromised extensions, \"HashJack\"-style prompt-injection in URLs, or spoofed AI sidebars trick assist"
  },
  {
    "code": "DSGAI17",
    "title": "Data Availability & Resilience Failures in AI Pipelines",
    "priority": "medium",
    "overview": "RAG-dependent applications have a data integrity dependency that does not exist in traditional software: the correctness of every response is contingent on the freshness, consistency, and availability of the underlying vector store and retrieval index at query time. When that layer degrades, the failure mode is not simply a 503 error -- it is silent misinformation at inference time, often indistin"
  },
  {
    "code": "DSGAI18",
    "title": "Inference & Data Reconstruction",
    "priority": "high",
    "overview": "Attackers iterate queries to infer membership (was X in training?) or reconstruct attributes/samples (model inversion). Embedding Inversion is a related technique where adversaries approximate original text via nearest neighbors or exploit confidence differences in the vector store. Even models not returning text can leak via probability scores or embedding similarities. These should be treated as"
  },
  {
    "code": "DSGAI19",
    "title": "Human-in-the-Loop & Labeler Overexposure",
    "priority": "medium",
    "overview": "For RLHF, safety fine-tuning, and data quality review, human labelers are given raw prompts, completions, internal documents, or conversation transcripts. Tasks are outsourced to vendors or crowd platforms with weak controls. Labelers can screenshot or exfiltrate sensitive data, or their endpoints can be compromised. Pseudonymization is often absent or flawed."
  },
  {
    "code": "DSGAI20",
    "title": "Model Exfiltration & IP Replication",
    "priority": "high",
    "overview": "Model Exfiltration Attacks (MEA), often referred to as distillation attacks, occur when an adversary uses legitimate API access to systematically and repeatedly probe a proprietary model (the \"teacher\" model) to extract its underlying logic, behavior, and capabilities. The attacker uses the massive set of input and teacher model output pairs to train a smaller, derivative model (the \"student\" mode"
  },
  {
    "code": "DSGAI21",
    "title": "Disinformation & Integrity Attacks via Data Poisoning",
    "priority": "critical",
    "overview": "Disinformation becomes a data security attack when an adversary deliberately introduces false, misleading, or manipulated data into a source that an AI system trusts -- a training corpus, a vector knowledge store, a retrieval index, a tool output, or a live data feed -- with the intent of causing the system to encode and surface that false information as authoritative to downstream users or automa"
  }
];
