import type { VercelRequest, VercelResponse } from '@vercel/node';

// =============================================================================
// VERCEL SERVERLESS CHATBOT — DOWNGRADED CAPABILITIES
// =============================================================================
// This handler is the Vercel-serverless counterpart of the NestJS
// ChatbotController (backend/apps/api-gateway/src/chatbot/chatbot.controller.ts).
//
// Key differences vs the NestJS path :
//   - NO MCP tool calling (the 32 MCP tools live in NestJS only)
//   - NO ReAct loop (single-shot Gemini call only)
//   - NO WebSocket streaming (REST one-shot response)
//   - Inline DSGAI summary (22 codes) is the only cited referential here
//   - Other referentials (PSSI 172 SIA, COMPASS 31, AST 29, AI Risk DB 1579)
//     are NOT available in this mode because the inline payload would exceed
//     the Vercel Lambda bundle size budget
//
// For full agentic capabilities, deploy the NestJS backend (Docker, Render,
// Railway, Fly.io, self-hosted) and point the frontend VITE_API_URL at it.
// The frontend banner explains this when isServerless=true.
// =============================================================================

// <DSGAI_SUMMARY_BEGIN>
// AUTO-GENERATED by scripts/extract-dsgai-json.cjs — do not edit manually.
// Regenerate: node scripts/extract-dsgai-json.cjs
interface DsgaiSummaryItem {
  code: string;
  title: string;
  priority?: 'critical' | 'high' | 'medium' | 'low';
  overview: string;
}
const DSGAI_SUMMARY: DsgaiSummaryItem[] = [
  {
    "code": "DSPM",
    "title": "DSPM for GenAI (AI-DSPM)",
    "priority": "medium",
    "overview": "AI-DSPM (Data Security Posture Management) for GenAI is the continuous practice of discovering, classifying, governing, and monitoring data across GenAI pipelines and runtimes, so you can see where sensitive data exists, understand how it flows/derives (e.g., into embeddings or logs), and enforce controls that prevent exposure, tampering, and non-compliance."
  },
  {
    "code": "DSGAI01",
    "title": "Sensitive Data Leakage",
    "priority": "critical",
    "overview": "An attacker (or a curious user) interacts with the model or a RAG system that was trained on to retrieve sensitive corporate data. Through carefully crafted instructions, enumeration, or high-recall prompts, the system returns verbatim or near-verbatim sensitive strings (PII/PHI/secrets/IP). Large models can unintentionally restate secrets from training data even without specific user prompting. F"
  },
  {
    "code": "DSGAI02",
    "title": "Agent Identity & Credential Exposure",
    "priority": "critical",
    "overview": "AI agent pipelines generate a rapidly expanding surface of Non-Human Identities (NHIs) -- service accounts, API keys, OAuth tokens, and tool credentials -- that accumulate across orchestration layers with little lifecycle governance. The core vulnerability is one of architectural mismatch: three-legged OAuth flows were designed around human consent, where a user actively delegates a bounded scope "
  },
  {
    "code": "DSGAI03",
    "title": "Shadow AI & Unsanctioned Data Flows",
    "priority": "high",
    "overview": "Business units experiment with public AI SaaS tools, browser plugins, and \"productivity\" agents without security review. Employees paste customer records, internal designs, or source code into these tools. Vendors may retain and train on this data, store it in third-country regions, or expose it via misconfigurations. No formal lineage, DSR handling, or contractual guarantees exist. Shadow AI enco"
  },
  {
    "code": "DSGAI04",
    "title": "Data, Model & Artifact Poisoning",
    "priority": "critical",
    "overview": "The full attack lifecycle moves through three stages that are operationally distinct but technically continuous. Understanding them separately is useful for detection; treating them as separate risks is not. Stage 1 -- Supply chain compromise: AI stacks ingest datasets, pre-trained models, packages, and tools from external sources with varying levels of trust verification. An adversary who control"
  },
  {
    "code": "DSGAI05",
    "title": "Data Integrity & Validation Failures",
    "priority": "high",
    "overview": "AI pipelines ingest data from a wide range of sources -- uploaded files, API feeds, snapshot imports, labeling queues, and third-party data connectors -- and the validation applied at each ingestion boundary is frequently insufficient to catch payloads that are structurally valid but semantically malicious or deliberately crafted to exploit the import mechanism itself. This creates two related but"
  },
  {
    "code": "DSGAI06",
    "title": "Tool, Plugin & Agent Data Exchange Risks",
    "priority": "critical",
    "overview": "Every tool invocation, plugin call, or agent handoff is a potential exfiltration boundary. When an AI assistant calls a plugin, forwards a task to a sub-agent, or receives instructions from an orchestrator, it typically shares all or part of the active conversation context -- including secrets, internal URLs, credentials, PII, and attachments -- with the receiving endpoint. If that endpoint is mal"
  },
  {
    "code": "DSGAI07",
    "title": "Data Governance, Lifecycle & Classification for AI Systems",
    "priority": "high",
    "overview": "In conventional data systems, a governance failure -- missing classification label, expired retention policy, absent lineage record -- is contained to the layer where it occurs. In AI pipelines, the same failure propagates forward and embeds itself in derived artifacts that outlive the source data, are difficult to enumerate, and are in many cases technically irreversible. This propagation dynamic"
  },
  {
    "code": "DSGAI08",
    "title": "Non-Compliance & Regulatory Violations",
    "priority": "medium",
    "overview": "Regulatory exposure in AI systems rarely originates as a discrete event -- it surfaces when technical risks documented elsewhere in this framework go unmitigated and intersect with enforceable legal obligations. Three failure patterns are worth distinguishing, as each triggers different regulatory mechanisms. The first is unlawful basis and consent failure: training data collected without a docume"
  },
  {
    "code": "DSGAI09",
    "title": "Multimodal Capture & Cross-Channel Data Leakage",
    "priority": "high",
    "overview": "Users upload screenshots of dashboards, photos of whiteboards, scans of passports, PDFs, and voice notes so multimodal assistants can \"understand context.\" These files are processed and retained in object stores, embeddings, and logs. The extracted text is as sensitive as the image itself. When images are OCR'd or audio transcribed, the resulting text must carry the same classification as the orig"
  },
  {
    "code": "DSGAI10",
    "title": "Synthetic Data, Anonymization & Transformation Pitfalls",
    "priority": "medium",
    "overview": "The core failure is an assumption that data transformation -- de-identification, tokenization, normalization, or synthetic generation -- produces a privacy guarantee it does not actually provide. This manifests across the data pipeline in three related ways. The first is anonymization and de-identification reversal: quasi-identifiers that survive transformation (age bands, ZIP codes, rare diagnosi"
  },
  {
    "code": "DSGAI11",
    "title": "Cross-Context & Multi-User Conversation Bleed",
    "priority": "critical",
    "overview": "LLM systems reuse conversation state or shared memory across sessions, tenants, or users to create \"persistent assistants.\" Weak isolation between workspaces, mishandled conversation IDs, or bugs in session management cause content from one user/tenant to appear in another's context window or RAG index. We saw this in March 2023 where a ChatGPT bug exposed users' conversation titles to others due "
  },
  {
    "code": "DSGAI12",
    "title": "Unsafe Natural-Language Data Gateways (LLM- to-SQL/Graph)",
    "priority": "high",
    "overview": "Organizations expose data warehouses, graphs, and analytics engines via \"Ask your data\" copilots. The LLM is allowed to generate raw SQL/GraphQL/REST queries over wide schemas. Prompt injection, hallucinated queries, or mis-specified policies lead to overly broad SELECTs, joins that cross tenants, or leaking sensitive columns. Weak validation means the generated queries execute as-is with elevated"
  },
  {
    "code": "DSGAI13",
    "title": "Vector Store Platform Data Security",
    "priority": "critical",
    "overview": "Unencrypted embeddings and permissive vector APIs allow similarity queries to surface sensitive content. Misconfigured and permissive vector APIs, unencrypted data at rest, or long-lived credentials allow unauthorized users to access and exfiltrate the raw embeddings and related metadata. Platform-level flaws (path traversal / arbitrary upload) can escalate to data theft or RCE, compromising entir"
  },
  {
    "code": "DSGAI14",
    "title": "Excessive Telemetry & Monitoring Leakage",
    "priority": "medium",
    "overview": "Teams instrument every request/response with rich logs, traces, and session captures to debug agent workflows and RAG quality. Logging middleware dumps full prompts, tool outputs, vector results, and credentials into centralized observability stacks. Highlight for third-party risk, if using external log analytic services, ensure they are secured to the same standard. Even limited data in logs can "
  },
  {
    "code": "DSGAI15",
    "title": "Over-Broad Context Windows & Prompt Over- Sharing",
    "priority": "high",
    "overview": "To \"improve answers,\" teams pack prompts with full user profiles, tickets, transaction histories, and document blobs. LLM gateways automatically append rich context (e.g., \"customer_360\") to every request. These payloads are sent to external API providers, cached by edge services, and logged for debugging. A breach at the provider, misconfigured cache, or insider with log access now has a 360� vie"
  },
  {
    "code": "DSGAI16",
    "title": "Endpoint & Browser Assistant Overreach",
    "priority": "high",
    "overview": "Users install AI browser extensions and OS/IDE copilots that promise productivity boosts. These tools request broad permissions (\"read and change all your data on websites you visit,\" \"read files in this folder,\" etc.) and stream page content, keystrokes, and code to remote LLM APIs. Malicious or compromised extensions, \"HashJack\"-style prompt-injection in URLs, or spoofed AI sidebars trick assist"
  },
  {
    "code": "DSGAI17",
    "title": "Data Availability & Resilience Failures in AI Pipelines",
    "priority": "medium",
    "overview": "RAG-dependent applications have a data integrity dependency that does not exist in traditional software: the correctness of every response is contingent on the freshness, consistency, and availability of the underlying vector store and retrieval index at query time. When that layer degrades, the failure mode is not simply a 503 error -- it is silent misinformation at inference time, often indistin"
  },
  {
    "code": "DSGAI18",
    "title": "Inference & Data Reconstruction",
    "priority": "high",
    "overview": "Attackers iterate queries to infer membership (was X in training?) or reconstruct attributes/samples (model inversion). Embedding Inversion is a related technique where adversaries approximate original text via nearest neighbors or exploit confidence differences in the vector store. Even models not returning text can leak via probability scores or embedding similarities. These should be treated as"
  },
  {
    "code": "DSGAI19",
    "title": "Human-in-the-Loop & Labeler Overexposure",
    "priority": "medium",
    "overview": "For RLHF, safety fine-tuning, and data quality review, human labelers are given raw prompts, completions, internal documents, or conversation transcripts. Tasks are outsourced to vendors or crowd platforms with weak controls. Labelers can screenshot or exfiltrate sensitive data, or their endpoints can be compromised. Pseudonymization is often absent or flawed."
  },
  {
    "code": "DSGAI20",
    "title": "Model Exfiltration & IP Replication",
    "priority": "high",
    "overview": "Model Exfiltration Attacks (MEA), often referred to as distillation attacks, occur when an adversary uses legitimate API access to systematically and repeatedly probe a proprietary model (the \"teacher\" model) to extract its underlying logic, behavior, and capabilities. The attacker uses the massive set of input and teacher model output pairs to train a smaller, derivative model (the \"student\" mode"
  },
  {
    "code": "DSGAI21",
    "title": "Disinformation & Integrity Attacks via Data Poisoning",
    "priority": "critical",
    "overview": "Disinformation becomes a data security attack when an adversary deliberately introduces false, misleading, or manipulated data into a source that an AI system trusts -- a training corpus, a vector knowledge store, a retrieval index, a tool output, or a live data feed -- with the intent of causing the system to encode and surface that false information as authoritative to downstream users or automa"
  }
];
// <DSGAI_SUMMARY_END>

// <PSSI_SUMMARY_BEGIN>
// AUTO-GENERATED by scripts/extract-pssi-summary.cjs — do not edit manually.
// Regenerate: node scripts/extract-pssi-summary.cjs
// Source: data_ai_risk/PSSI_IA_v3_CONSOLIDE.pdf (172 exigences SIA-001..SIA-172).
interface PssiSummaryItem { id: string; chapterNumber: string; ruleText: string; }
interface PssiChapterIndex { number: string; title: string; count: number; }
const PSSI_SUMMARY: PssiSummaryItem[] = [
  {
    "id": "SIA-001",
    "chapterNumber": "2",
    "ruleText": "Le Groupe doit tenir à jour un inventaire exhaustif de ses systèmes d'intelligence artificielle, couvrant SIA internes, acquis, embarqués, publics utilisés, et SIA en POC, avec rattachement à un propriétaire métier identifié."
  },
  {
    "id": "SIA-002",
    "chapterNumber": "2",
    "ruleText": "Le Groupe ne doit déployer ni utiliser aucun système d'IA relevant des pratiques prohibées listées à l'article 5 de l'AI Act, y compris à titre expérimental, et doit disposer d'un contrôle de conformité explicite en amont de toute validation de projet IA."
  },
  {
    "id": "SIA-003",
    "chapterNumber": "2",
    "ruleText": "Tout SIA intégrant une composante d'apprentissage automatique ou de modèle statistique auto-adaptatif doit faire l'objet d'une qualification formelle (IN / OUT de périmètre) documentée par le RSSI avant tout développement ou mise en production."
  },
  {
    "id": "SIA-004",
    "chapterNumber": "5",
    "ruleText": "Le Groupe doit disposer d'une instance Comité IA formellement mandatée, se réunissant au moins mensuellement, disposant d'un règlement intérieur, d'un quorum défini et d'une capacité décisionnelle opposable."
  },
  {
    "id": "SIA-005",
    "chapterNumber": "5",
    "ruleText": "Tout projet SIA doit être soumis au Comité IA pour validation avant passage en phase de développement, avec dossier comportant : qualification AI Act, classification tier, AIPD le cas échéant, Model Card prévisionnelle, Risk Card prévisionnelle, plan de tests "
  },
  {
    "id": "SIA-006",
    "chapterNumber": "5",
    "ruleText": "que SIA doit avoir un propriétaire métier nommément désigné, responsable de la finalité, du ROI, de la conformité d'usage et porteur ultime la décision de retrait. Le propriétaire métier ne peut être une fonction port ni la DSI."
  },
  {
    "id": "SIA-007",
    "chapterNumber": "5",
    "ruleText": "Le RSSI doit disposer d'un droit de veto effectif et opposable sur la mise en production de tout SIA pour motif de sécurité, sans que ce veto ne puisse être levé par une instance autre que le Comité des Risques après avis circonstancié."
  },
  {
    "id": "SIA-008",
    "chapterNumber": "5",
    "ruleText": "Le DPO doit disposer d'un droit de veto effectif et opposable sur la mise en production de tout SIA pour motif de non-conformité au RGPD, à l'AI Act ou à toute autre exigence de protection des données, selon le même régime que SIA-007."
  },
  {
    "id": "SIA-009",
    "chapterNumber": "5",
    "ruleText": "Pour chaque SIA de tier AISVS L2 ou L3, un Model Steward et un Data Steward distincts doivent être nominativement désignés, indépendants des équipes de développement, chargés respectivement du suivi du modèle et des données sur l'ensemble du cycle de vie."
  },
  {
    "id": "SIA-010",
    "chapterNumber": "5",
    "ruleText": "Toute dérogation à la présente politique doit faire l'objet d'une demande formelle motivée, instruite par le RSSI et le DPO, validée par le Comité IA pour les dérogations tier AISVS L1-L2 et par le Comité des Risques pour les dérogations tier AISVS L3 ou AI Ac"
  },
  {
    "id": "SIA-011",
    "chapterNumber": "5",
    "ruleText": "La Direction Générale doit allouer annuellement un budget dédié à la sécurité IA, distinct du budget cyber général, couvrant formation, outillage, red teaming, audit et incident response. Le dimensionnement est proposé par le RSSI sur la base du portefeuille S"
  },
  {
    "id": "SIA-012",
    "chapterNumber": "5",
    "ruleText": "L'Audit interne doit conduire annuellement un audit de conformité à la présente politique couvrant au moins : gouvernance, tiering, cycle de vie d'un échantillon représentatif de SIA, gestion des incidents, registre des dérogations, supply chain IA."
  },
  {
    "id": "SIA-013",
    "chapterNumber": "5",
    "ruleText": "La Cellule de Crise IA doit être activable sous 30 minutes ouvrées et sous 2 heures non ouvrées, disposer de procédures écrites, d'un annuaire de crise à jour et d'exercices de simulation au moins semestriels."
  },
  {
    "id": "SIA-014",
    "chapterNumber": "6",
    "ruleText": "Tout SIA doit être classé selon la typologie de conformité externe de l'AI Act : pratiques prohibées (art. 5), haut risque (art. 6 + annexe III), GPAI à risque systémique (art. 51), GPAI (art. 3(63)), risque limité relevant de transparence (art. 50), ou risque"
  },
  {
    "id": "SIA-015",
    "chapterNumber": "6",
    "ruleText": "Tout SIA doit être classé selon la posture de sécurité interne sur l'échelle AISVS : Level 1 (baseline), Level 2 (standard), ou Level 3 (advanced), indépendamment de sa qualification AI Act. Le classement reflète l'exposition interne et le besoin de contrôles."
  },
  {
    "id": "SIA-016",
    "chapterNumber": "6",
    "ruleText": "Le tier applicable à un SIA est déterminé par la matrice à deux dimensions (AI Act × AISVS) publiée par le RSSI. La cellule cible définit le socle de contrôles minimum applicable. Tout SIA relevant de l'AI Act haut risque est automatiquement classé au minimum "
  },
  {
    "id": "SIA-017",
    "chapterNumber": "6",
    "ruleText": "Le tier déterminé par la matrice doit être propagé automatiquement sur l'ensemble des exigences applicables du cycle de vie via le registre central. Les chapitres 7 à 14 listent, pour chaque exigence, les tiers pour lesquels elle est applicable."
  },
  {
    "id": "SIA-018",
    "chapterNumber": "6",
    "ruleText": "Le tier doit être réévalué à la survenue de tout événement déclencheur : changement de finalité, extension de périmètre d'utilisateurs ou de données, incident de sécurité majeur ou critique, évolution réglementaire, modification substantielle du modèle, ou au "
  },
  {
    "id": "SIA-019",
    "chapterNumber": "6",
    "ruleText": "Le tier de chaque SIA doit être publié dans le registre central et communiqué aux équipes opérationnelles, au propriétaire métier, au Model Steward, au Data Steward et aux éventuels fournisseurs impactés. Le tier n'est pas confidentiel en interne."
  },
  {
    "id": "SIA-020",
    "chapterNumber": "6",
    "ruleText": "Le Groupe doit publier annuellement un rapport consolidé de tiering présentant la distribution des SIA par cellule de la matrice AI Act × AISVS, les re-classifications de l'année, les SIA retirés, et les tendances d'évolution du portefeuille IA. ISO 42001 §9.3"
  },
  {
    "id": "SIA-021",
    "chapterNumber": "7",
    "ruleText": "Tout SIA doit faire l'objet d'un threat modeling formel en phase de conception, couvrant au minimum les cinq catégories d'attaques de l'AML selon ISO 27090 : evasion, poisoning, extraction, inference et failure. Le threat model utilise MITRE ATLAS comme taxono"
  },
  {
    "id": "SIA-022",
    "chapterNumber": "7",
    "ruleText": "Tout SIA relevant de l'AI Act haut risque ou traitant des données RGPD art. 9 doit faire l'objet d'une AIIA (AI Impact Assessment) et d'une AIPD (Analyse d'Impact relative à la Protection des Données) coordonnées, validées avant la phase de développement."
  },
  {
    "id": "SIA-023",
    "chapterNumber": "7",
    "ruleText": "L'architecture d'un SIA devrait appliquer les principes zero-trust : authentification forte de tous les appels au modèle, micro-segmentation réseau, moindre privilège appliqué aux pipelines de training et d'inférence, chiffrement en transit et au repos."
  },
  {
    "id": "SIA-024",
    "chapterNumber": "7",
    "ruleText": "La décision de construire, d'utiliser un modèle existant (avec ou sans fine- tuning) ou de consommer une API externe doit faire l'objet d'une analyse comparative documentée couvrant : posture sécurité du fournisseur, maîtrise des données, souveraineté, coûts, "
  },
  {
    "id": "SIA-025",
    "chapterNumber": "7",
    "ruleText": "La sélection d'un modèle doit considérer explicitement : complexité du modèle, adéquation au cas d'usage, capacité d'explicabilité, caractéristiques des datasets d'entraînement (qualité, représentativité, sensibilité, âge, diversité), provenance et chaîne d'ap"
  },
  {
    "id": "SIA-026",
    "chapterNumber": "7",
    "ruleText": "Les composants logiciels d'un SIA doivent être développés dans des environnements sécurisés en appliquant les pratiques DevSecOps : intégration continue avec tests de sécurité automatisés, revue de code systématique, scan de secrets, scan SAST et SCA, validati"
  },
  {
    "id": "SIA-027",
    "chapterNumber": "7",
    "ruleText": "Les environnements de recherche, de développement, de pré-production et de production doivent être strictement isolés. Aucune donnée de production ne doit être utilisée dans les environnements de développement sans anonymisation ou pseudonymisation préalable."
  },
  {
    "id": "SIA-028",
    "chapterNumber": "7",
    "ruleText": "Aucun secret (clé API, identifiants, tokens, poids de modèle propriétaire) ne doit être stocké en clair dans le code, les notebooks, les configurations ou les logs. Un gestionnaire de secrets centralisé doit être utilisé avec rotation automatique."
  },
  {
    "id": "SIA-029",
    "chapterNumber": "7",
    "ruleText": "Chaque SIA de tier AISVS L2 ou L3 doit disposer d'une Model Card, d'une Data Card et d'une Risk Card à jour, couvrant finalité, données, métriques, limites, biais connus, risques et mitigations. Les prompts systèmes sont documentés comme actifs de même rang qu"
  },
  {
    "id": "SIA-030",
    "chapterNumber": "7",
    "ruleText": "Le Groupe doit identifier, suivre et gérer activement la dette technique IA sur chaque SIA : modèles obsolètes, versions superposées non consolidées, pipelines de données non maintenus, dépendances fin de vie, documentation lacunaire. Un registre de dette tech"
  },
  {
    "id": "SIA-031",
    "chapterNumber": "7",
    "ruleText": "La provenance et le lineage de toutes les données utilisées pour l'entraînement, le fine-tuning, l'évaluation et l'augmentation contextuelle (RAG) doivent être tracés et documentés, de la source primaire jusqu'à l'ingestion dans le SIA."
  },
  {
    "id": "SIA-032",
    "chapterNumber": "7",
    "ruleText": "Des contrôles de détection d'empoisonnement des données d'entraînement, de fine-tuning et de feedback doivent être appliqués : détection d'anomalies statistiques, vérification de cohérence, isolation des sources externes non fiables, tests de robustesse post-e"
  },
  {
    "id": "SIA-033",
    "chapterNumber": "7",
    "ruleText": "Toutes les composantes d'un SIA — modèles, poids, datasets, checkpoints, prompts systèmes, configurations — doivent être versionnées dans un système de gestion de versions dédié, permettant la reproductibilité et le retour à un état antérieur."
  },
  {
    "id": "SIA-034",
    "chapterNumber": "7",
    "ruleText": "Tout fichier de poids de modèle, tout dataset d'entraînement majeur et tout prompt système doit disposer d'un hachage cryptographique (SHA-256 minimum) et, pour les artefacts déployés, d'une signature cryptographique (ECDSA P-256 ou Ed25519). La vérification d"
  },
  {
    "id": "SIA-035",
    "chapterNumber": "7",
    "ruleText": "Avant toute mise en production, un SIA doit faire l'objet de tests fonctionnels documentés couvrant précision, rappel, cohérence, robustesse aux variations d'entrée et performance opérationnelle, avec seuils minimaux définis par le Model Steward."
  },
  {
    "id": "SIA-036",
    "chapterNumber": "7",
    "ruleText": "Tout SIA prenant ou influençant des décisions affectant des personnes doit faire l'objet de tests de biais et de fairness documentés (disparate impact, equalized odds, demographic parity selon le cas), avec critères d'acceptation définis et mitigations appliqu"
  },
  {
    "id": "SIA-037",
    "chapterNumber": "7",
    "ruleText": "Tout SIA de tier AISVS L2 ou L3 doit faire l'objet de tests adversariaux documentés couvrant prompt injection, jailbreak, extraction, inference, evasion, en utilisant des outils reconnus (ART, CleverHans, Garak ou équivalents)."
  },
  {
    "id": "SIA-038",
    "chapterNumber": "7",
    "ruleText": "Tout SIA de tier AISVS L3 ou AI Act haut risque doit faire l'objet d'une campagne de red teaming formelle avant mise en production, réalisée par une équipe distincte de l'équipe de développement, avec rapport opposable et plan de remédiation. CLUSIF SIA-14 ; A"
  },
  {
    "id": "SIA-039",
    "chapterNumber": "7",
    "ruleText": "Aucun SIA ne peut être mis en production sans franchissement documenté d'un Security Gate validant : threat model à jour, tests TEVV passés, documentation complète, plan de rollback, plan d'incident, validation RSSI et DPO."
  },
  {
    "id": "SIA-040",
    "chapterNumber": "7",
    "ruleText": "Chaque SIA de tier AISVS L2 ou L3 doit disposer d'un plan de rollback testé permettant le retour à la version stable précédente en moins de 24 heures ouvrées pour L2 et en moins de 4 heures pour L3. ISO 42001 §8.1 ; DORA art. 11 Plan de rollback documenté ; ex"
  },
  {
    "id": "SIA-041",
    "chapterNumber": "7",
    "ruleText": "Tout SIA de tier AISVS L3, tout SIA AI Act haut risque et tout système agentique (voir ch. 10) doit disposer d'un kill switch permettant son arrêt immédiat par un opérateur autorisé, testé semestriellement. OWASP AISVS Ch. 9 ; AI Act art. 14 Procédure document"
  },
  {
    "id": "SIA-042",
    "chapterNumber": "7",
    "ruleText": "Chaque SIA de tier AISVS L2 ou L3 doit disposer de circuit breakers —"
  },
  {
    "id": "SIA-043",
    "chapterNumber": "7",
    "ruleText": "Les mises à jour de modèles, poids, prompts systèmes et configurations doivent suivre une procédure sécurisée : tests de régression en pré- production, canarisation sur un sous-ensemble contrôlé, monitoring renforcé post-déploiement sur au moins 72 heures, et "
  },
  {
    "id": "SIA-044",
    "chapterNumber": "7",
    "ruleText": "Chaque SIA en exploitation doit faire l'objet d'un monitoring continu du drift : dérive des distributions d'entrée, dérive des performances, dérive des distributions de sortie, avec seuils d'alerte et actions automatiques définies. CLUSIF SIA-15 ; ISO 42001 §B"
  },
  {
    "id": "SIA-045",
    "chapterNumber": "7",
    "ruleText": "Toutes les entrées d'un SIA — requêtes, prompts, fichiers joints, contextes — doivent être journalisées de manière immuable, avec horodatage, identifiant utilisateur, identifiant session, et hachage du contenu, dans le respect du RGPD et des politiques de mini"
  },
  {
    "id": "SIA-046",
    "chapterNumber": "7",
    "ruleText": "Un dispositif de détection d'anomalies comportementales couvrant les entrées, les sorties et les métriques internes du modèle doit être déployé sur tout SIA de tier AISVS L2 ou L3, avec escalade automatique au SOC en cas d'incident suspect."
  },
  {
    "id": "SIA-047",
    "chapterNumber": "7",
    "ruleText": "Les sorties générées par un SIA doivent faire l'objet de validations et d'un DLP sortant adapté à la sensibilité du contexte : scan contre les exfiltrations de PII, contre les fuites de secrets, contre les contenus inappropriés, avec blocage ou mise en quarant"
  },
  {
    "id": "SIA-048",
    "chapterNumber": "7",
    "ruleText": "Le retrait d'un SIA doit suivre une procédure formelle couvrant : destruction sécurisée des données (RGPD art. 17), retrait contrôlé du modèle, archivage de la documentation légalement requise, information des utilisateurs et des parties prenantes, retour d'ex"
  },
  {
    "id": "SIA-049",
    "chapterNumber": "8",
    "ruleText": "Toutes les sources de données des pipelines IA — data warehouses, data lakes, vector stores, bases documentaires, APIs internes et externes — doivent être inventoriées et cartographiées dans un registre unique data-IA, maintenu en continu."
  },
  {
    "id": "SIA-050",
    "chapterNumber": "8",
    "ruleText": "Chaque dataset utilisé par un SIA doit être classifié selon l'échelle de sensibilité du Groupe (Public / Interne / Confidentiel / Secret) et selon la typologie RGPD (données courantes / sensibles art. 9 / pénales art. 10). La classification conditionne les con"
  },
  {
    "id": "SIA-051",
    "chapterNumber": "8",
    "ruleText": "Les entrées transmises aux SIA doivent être filtrées en amont contre les injections de prompt, les contenus malveillants, les tentatives d'exfiltration d'instructions système, et les PII non autorisées selon le tier du SIA. OWASP LLM01 ; OWASP GenAI Data Secur"
  },
  {
    "id": "SIA-052",
    "chapterNumber": "8",
    "ruleText": "Les données personnelles transitant par un SIA doivent être masquées dynamiquement lorsque le tier ou la finalité ne justifient pas leur exposition en clair : tokenisation, pseudonymisation, k-anonymity, l-diversity selon le contexte."
  },
  {
    "id": "SIA-053",
    "chapterNumber": "8",
    "ruleText": "Les sorties d'un SIA doivent faire l'objet d'un scan post-génération visant à détecter les fuites de données sensibles, les PII non attendues, les secrets techniques et les contenus hors politique. Les détections critiques entraînent blocage de la sortie et al"
  },
  {
    "id": "SIA-054",
    "chapterNumber": "8",
    "ruleText": "La provenance de chaque donnée utilisée en entraînement ou en RAG doit être documentée dans la Data Card correspondante, incluant source primaire, date d'acquisition, licence, consentement applicable, transformations subies."
  },
  {
    "id": "SIA-055",
    "chapterNumber": "8",
    "ruleText": "Aucune donnée adhérent, patient, assuré ou bénéficiaire identifiable ou ré- identifiable ne doit être transmise à un SIA GPAI public ou à un service IA tiers hors maîtrise du Groupe, quel que soit le volume ou la finalité. Le non- respect constitue un manqueme"
  },
  {
    "id": "SIA-056",
    "chapterNumber": "8",
    "ruleText": "Les données collectées ou utilisées par un SIA doivent respecter le principe de minimisation : seules les données strictement nécessaires à la finalité déclarée sont collectées, traitées et conservées. Les finalités non explicitement déclarées sont interdites."
  },
  {
    "id": "SIA-057",
    "chapterNumber": "8",
    "ruleText": "Le traitement de données de santé par un SIA doit disposer de la base légale adéquate au sens du RGPD art. 9(2), s'effectuer sur infrastructure certifiée HDS, et faire l'objet d'une AIPD spécifique santé validée par le DPO et le médecin-conseil lorsque pertine"
  },
  {
    "id": "SIA-058",
    "chapterNumber": "8",
    "ruleText": "Les datasets d'entraînement comportant des données personnelles devraient être anonymisés ou pseudonymisés par défaut, sauf nécessité démontrée d'utilisation en clair documentée dans l'AIPD. RGPD art. 4(5), 25 ; CNIL guide anonymisation Data Card précisant l'é"
  },
  {
    "id": "SIA-059",
    "chapterNumber": "8",
    "ruleText": "Les durées de conservation des données utilisées par les SIA — données d'entraînement, embeddings, logs de prompts, feedbacks — doivent être définies par finalité, documentées, et faire l'objet de purges automatiques à l'échéance. Aucune donnée personnelle ne "
  },
  {
    "id": "SIA-060",
    "chapterNumber": "8",
    "ruleText": "Toutes les opérations du pipeline de données IA — ingestion, transformation, accès, suppression, export — doivent être journalisées de manière immuable avec chaînage cryptographique, permettant la preuve intègre en cas d'investigation."
  },
  {
    "id": "SIA-061",
    "chapterNumber": "8",
    "ruleText": "Les embeddings dérivés de données sensibles doivent être chiffrés au repos, stockés sur infrastructure maîtrisée, soumis aux mêmes contrôles d'accès que les données originales, et purgés en cas de retrait du consentement ou d'exercice du droit à l'oubli."
  },
  {
    "id": "SIA-062",
    "chapterNumber": "9",
    "ruleText": "Toute acquisition de composant IA — modèle, dataset, bibliothèque, service SaaS, API — doit être précédée d'une due diligence sécurité formelle couvrant : posture sécurité du fournisseur, certifications, hébergement, garanties contractuelles, audit right, réve"
  },
  {
    "id": "SIA-063",
    "chapterNumber": "9",
    "ruleText": "Les fournisseurs de composants IA doivent être certifiés a minima ISO 27001 ; HDS pour tout composant traitant des données de santé ; SecNumCloud est recommandé (et non obligatoire) pour tout composant classé en tier AISVS L3, priorité accordée aux offres qual"
  },
  {
    "id": "SIA-064",
    "chapterNumber": "9",
    "ruleText": "Les composants IA traitant des données sensibles du Groupe doivent être hébergés en France ou dans l'Union européenne, sur infrastructures exemptes de risque d'accès par une loi extraterritoriale non compatible RGPD. Les dérogations sont traitées selon SIA-010"
  },
  {
    "id": "SIA-065",
    "chapterNumber": "9",
    "ruleText": "Les contrats avec les fournisseurs IA doivent comporter une clause explicite de non-rétroaction interdisant au fournisseur d'utiliser les données du Groupe, les prompts, les outputs ou les feedbacks pour entraîner, affiner ou améliorer ses modèles, sauf accord"
  },
  {
    "id": "SIA-066",
    "chapterNumber": "9",
    "ruleText": "Chaque fournisseur de modèle ou de service IA doit fournir un AI-BOM à jour documentant : identité des modèles, versions, architectures, données d'entraînement (nature, sources, licences), dépendances, limites connues, modes de défaillance."
  },
  {
    "id": "SIA-067",
    "chapterNumber": "9",
    "ruleText": "Les SIA internes doivent disposer d'un SBOM étendu aux composants ML (modèles, datasets, frameworks, librairies) au format standard (CycloneDX- ML ou équivalent). Le SBOM est produit à chaque build et publié aux parties prenantes."
  },
  {
    "id": "SIA-068",
    "chapterNumber": "9",
    "ruleText": "Les dépendances des pipelines IA doivent être scannées automatiquement et quotidiennement contre des bases de vulnérabilités reconnues (CVE, GitHub Advisory, Snyk) avec remédiation priorisée selon la criticité CVSS. OWASP AISVS Ch. 6 ; ISO 27001 §8.8 ; DORA Ou"
  },
  {
    "id": "SIA-069",
    "chapterNumber": "9",
    "ruleText": "Les licences de tous les modèles, datasets et outils IA utilisés doivent être identifiées, documentées et respectées. Les licences incompatibles avec les finalités du Groupe sont interdites d'usage en production. OWASP AISVS Ch. 6 ; Code de la propriété intell"
  },
  {
    "id": "SIA-070",
    "chapterNumber": "9",
    "ruleText": "Les modèles tiers importés doivent être traités comme du code non fiable : vérification de signature, scan statique des fichiers de poids (recherche de code arbitraire dans Pickle, HDF5, SafeTensors), isolation en sandbox lors du premier chargement."
  },
  {
    "id": "SIA-071",
    "chapterNumber": "9",
    "ruleText": "Les contrats avec les fournisseurs IA critiques — au sens DORA art. 28 pour les services ICT — doivent comporter un droit d'audit annuel exerçable par le Groupe, par un tiers auditeur mandaté, ou par les autorités de tutelle."
  },
  {
    "id": "SIA-072",
    "chapterNumber": "9",
    "ruleText": "Chaque fournisseur IA critique doit faire l'objet d'une stratégie de sortie documentée permettant la migration ou l'internalisation du composant en cas de défaillance, rupture contractuelle, évolution réglementaire ou décision stratégique. La stratégie est tes"
  },
  {
    "id": "SIA-073",
    "chapterNumber": "9",
    "ruleText": "La performance opérationnelle et la posture sécurité des fournisseurs IA doivent être monitorées en continu : SLA, incidents, évolutions contractuelles, changements d'actionnariat, alertes CERT, avec remontée trimestrielle au Comité IA. DORA art. 28-30 ; NIS2 "
  },
  {
    "id": "SIA-074",
    "chapterNumber": "10",
    "ruleText": "Tout SIA doté d'une capacité d'action autonome sur son environnement — appel d'outils (tool use), modification de données, interaction avec des systèmes tiers, orchestration multi-agents — doit être qualifié comme système agentique et classé au minimum AISVS L"
  },
  {
    "id": "SIA-075",
    "chapterNumber": "10",
    "ruleText": "Chaque agent déployé doit disposer d'un AI-BOM agentique documentant : modèle sous-jacent, outils autorisés, permissions associées, chaînes d'appels inter-agents, serveurs MCP utilisés, sources de contexte. Cet AI- BOM est mis à jour à chaque évolution et soum"
  },
  {
    "id": "SIA-076",
    "chapterNumber": "10",
    "ruleText": "Les agents doivent opérer selon le principe de moindre privilège : chaque outil, chaque API, chaque accès à une source de données nécessite une autorisation explicite, restreinte au périmètre strictement nécessaire, documentée et auditée. Aucune permission glo"
  },
  {
    "id": "SIA-077",
    "chapterNumber": "10",
    "ruleText": "L'utilisation du Model Context Protocol doit respecter un cadre de sécurité renforcé : manifests MCP signés cryptographiquement, allowlist explicite des serveurs MCP autorisés, scope des outils limité et documenté, mécanismes de révocation immédiate, surveilla"
  },
  {
    "id": "SIA-078",
    "chapterNumber": "10",
    "ruleText": "Toute action d'un agent sur un système tiers — écriture de fichier, envoi d'email, appel d'API modifiante, exécution de commande — doit se dérouler dans un environnement d'exécution confiné (sandbox) permettant l'audit, la limitation des effets et la révocatio"
  },
  {
    "id": "SIA-079",
    "chapterNumber": "10",
    "ruleText": "Toutes les actions d'un agent doivent être journalisées de manière immuable, avec horodatage, identifiant agent, identifiant session, nom de l'outil appelé, paramètres, résultat, décision associée du modèle et justification textuelle. La journalisation est aud"
  },
  {
    "id": "SIA-080",
    "chapterNumber": "10",
    "ruleText": "Chaque agent doit disposer d'un kill switch dédié, distinct du kill switch du modèle sous-jacent (SIA-041), permettant l'arrêt immédiat de l'ensemble des actions en cours et le blocage de toute nouvelle action, sans latence supérieure à 30 secondes. Le kill sw"
  },
  {
    "id": "SIA-081",
    "chapterNumber": "10",
    "ruleText": "Toute action d'un agent ayant une conséquence financière, juridique, contractuelle, ou un impact sur un adhérent, un assuré ou un bénéficiaire, doit faire l'objet d'une confirmation humaine explicite préalable (HITL niveau 4), sauf exemption documentée et vali"
  },
  {
    "id": "SIA-082",
    "chapterNumber": "10",
    "ruleText": "Les agents ne peuvent exécuter de manière autonome aucune action relevant des catégories suivantes : exécution de paiements, modification de contrats, transmission de données adhérents vers un tiers, modification de droits d'accès, décision sur prestation sant"
  },
  {
    "id": "SIA-083",
    "chapterNumber": "10",
    "ruleText": "Les agents doivent être soumis à des quotas et rate limits paramétrés : nombre maximum d'appels d'outils par session, coût maximum par exécution, profondeur maximum des chaînes d'appels, durée maximum d'exécution, avec arrêt automatique en cas de dépassement e"
  },
  {
    "id": "SIA-084",
    "chapterNumber": "10",
    "ruleText": "Les agents doivent faire l'objet de tests spécifiques avant mise en production, couvrant : injection de prompt via tool chaining, role confusion, détournement de contexte, excès d'autonomie, boucles infinies, escalade de privilèges via outils, ré-identificatio"
  },
  {
    "id": "SIA-085",
    "chapterNumber": "10",
    "ruleText": "La chaîne de responsabilité pour les actions des agents doit être formellement établie et documentée : l'imputabilité finale d'une action revient au propriétaire métier du SIA ; l'opérateur de supervision est responsable du contrôle en temps réel ; l'équipe te"
  },
  {
    "id": "SIA-086",
    "chapterNumber": "11",
    "ruleText": "Il est interdit d'utiliser un outil d'IA générative pour produire des blocs de code destinés aux modules suivants : cryptographie (authentification, chiffrement, signature, gestion de clés), gestion des droits et des accès utilisateurs et administrateurs, trai"
  },
  {
    "id": "SIA-087",
    "chapterNumber": "11",
    "ruleText": "L'exécution automatique de code source généré par IA dans les environnements de développement, de pré-production ou de production est interdite. Tout code généré par IA doit être explicitement soumis à exécution par un développeur humain dans un environnement "
  },
  {
    "id": "SIA-088",
    "chapterNumber": "11",
    "ruleText": "Le commit automatique de code source généré par IA dans les dépôts est interdit. Tout commit comportant du code généré par IA doit être précédé d'une revue humaine attestée, explicitement tracée dans le message de commit ou l'historique de la pull request."
  },
  {
    "id": "SIA-089",
    "chapterNumber": "11",
    "ruleText": "Tout code source généré par IA doit être soumis à un pipeline de vérification automatisée comportant au minimum : analyse statique (SAST), scan de secrets, analyse de composition logicielle (SCA), linting sécurité. Les vulnérabilités critiques ou hautes doiven"
  },
  {
    "id": "SIA-090",
    "chapterNumber": "11",
    "ruleText": "Les bibliothèques, paquets et dépendances référencés par le code généré par IA doivent être vérifiés avant utilisation : existence réelle du paquet (détection des hallucinations de packages), vérification de la réputation, scan de vulnérabilités, conformité de"
  },
  {
    "id": "SIA-091",
    "chapterNumber": "11",
    "ruleText": "Toute pull request comportant du code généré par IA doit faire l'objet d'une revue de code humaine attestée par un développeur distinct de celui ayant sollicité la génération, avec examen explicite des risques spécifiques : hallucinations, vulnérabilités intro"
  },
  {
    "id": "SIA-092",
    "chapterNumber": "11",
    "ruleText": "Le Groupe doit conduire des campagnes périodiques de contrôle de qualité du code généré par IA : analyse d'échantillons représentatifs, comparaison qualité code généré vs code humain, taux de vulnérabilités introduites, taux de fausses dépendances détectées. L"
  },
  {
    "id": "SIA-093",
    "chapterNumber": "11",
    "ruleText": "Les développeurs utilisant des outils de génération de code par IA doivent suivre une formation initiale obligatoire (4h minimum) et une sensibilisation annuelle, couvrant : risques spécifiques, modules interdits, techniques de prompt engineering sécurisé, obl"
  },
  {
    "id": "SIA-094",
    "chapterNumber": "11",
    "ruleText": "Les sollicitations des outils de génération de code — prompts envoyés, réponses générées, code finalement intégré — doivent être journalisées pour les périmètres sensibles, permettant la traçabilité en cas d'incident ou d'audit, dans le respect des obligations"
  },
  {
    "id": "SIA-095",
    "chapterNumber": "11",
    "ruleText": "L'utilisation d'outils de génération de code doit être limitée aux outils approuvés et référencés par le Groupe, exécutés sur infrastructure maîtrisée ou dans un cadre contractuel garantissant la non-rétroaction (voir SIA-065). L'usage d'outils personnels ou n"
  },
  {
    "id": "SIA-096",
    "chapterNumber": "12",
    "ruleText": "Chaque SIA doit être positionné explicitement sur l'échelle HITL du Groupe (niveaux 0 à 4) selon sa capacité d'action et l'impact de ses décisions. Le positionnement conditionne les obligations de supervision applicables et est cohérent avec le tiering du ch. "
  },
  {
    "id": "SIA-097",
    "chapterNumber": "12",
    "ruleText": "Les superviseurs humains de tout SIA de tier AI Act haut risque ou AISVS L2-L3 doivent disposer d'une connaissance suffisante des capacités et des limites du système, documentée par une formation initiale et une formation continue, et attestée par une évaluati"
  },
  {
    "id": "SIA-098",
    "chapterNumber": "12",
    "ruleText": "Les superviseurs doivent disposer d'interfaces et d'outils leur permettant de comprendre les sorties du SIA, de détecter les anomalies et les dérives, et d'obtenir des explications sur les décisions générées, à un niveau de détail adapté à leur rôle."
  },
  {
    "id": "SIA-099",
    "chapterNumber": "12",
    "ruleText": "Les superviseurs doivent disposer d'un pouvoir effectif d'intervention : correction, override, interruption, déclenchement du kill switch. Ce pouvoir est techniquement disponible sans délai et organisationnellement délégué sans escalade bloquante."
  },
  {
    "id": "SIA-100",
    "chapterNumber": "12",
    "ruleText": "Les superviseurs d'un SIA doivent disposer d'une autorité effective pour intervenir : position hiérarchique appropriée, délégation formelle, absence de contrainte organisationnelle les dissuadant d'exercer leur rôle (notamment pas d'objectifs de performance pr"
  },
  {
    "id": "SIA-101",
    "chapterNumber": "12",
    "ruleText": "Le dispositif de supervision doit prévenir le biais d'automation (sur-confiance dans la sortie du SIA) : alertes contextuelles, tests aveugles aléatoires, rotation des superviseurs, mesure du taux d'override et des désaccords, feedback aux superviseurs."
  },
  {
    "id": "SIA-102",
    "chapterNumber": "12",
    "ruleText": "Le temps d'exposition continue d'un superviseur à un SIA générant de grandes volumétries de décisions à valider devrait être limité, avec rotations, pauses prévues et diversification des tâches, afin de préserver la vigilance et d'éviter la fatigue décisionnel"
  },
  {
    "id": "SIA-103",
    "chapterNumber": "12",
    "ruleText": "Toute personne affectée par une décision significativement automatisée d'un SIA doit pouvoir exercer ses droits au titre de l'article 22 du RGPD : être informée, obtenir une explication, contester la décision, demander un réexamen humain. Les processus et outi"
  },
  {
    "id": "SIA-104",
    "chapterNumber": "13",
    "ruleText": "Tout SIA interagissant directement avec des personnes physiques — adhérents, assurés, collaborateurs, candidats — doit informer clairement ses interlocuteurs qu'ils interagissent avec un système d'intelligence artificielle, sauf si la nature de l'interaction r"
  },
  {
    "id": "SIA-105",
    "chapterNumber": "13",
    "ruleText": "Tout contenu synthétique (texte, image, audio, vidéo) généré par un SIA du Groupe et diffusé à l'extérieur doit être marqué de manière détectable par machine (watermarking) lorsque la technologie le permet, et accompagné d'une mention explicite lisible pour un"
  },
  {
    "id": "SIA-106",
    "chapterNumber": "13",
    "ruleText": "La production de deepfakes — contenus synthétiques représentant des personnes réelles de manière réaliste — est interdite sauf dans des cadres strictement encadrés : consentement explicite de la personne représentée, finalité légitime documentée, marquage renf"
  },
  {
    "id": "SIA-107",
    "chapterNumber": "13",
    "ruleText": "L'utilisation de GPAI publics (ChatGPT, Claude, Gemini, Perplexity, Copilot public, outils similaires) par les collaborateurs doit respecter la matrice d'autorisation par classification de données définie par le Groupe. Les données classées Confidentiel ou Sec"
  },
  {
    "id": "SIA-108",
    "chapterNumber": "13",
    "ruleText": "Aucune donnée adhérent, assuré, patient, bénéficiaire, candidat ou collaborateur identifiable ou ré-identifiable ne doit être transmise à un GPAI public ni à un service IA tiers non-souverain, quel que soit le volume, la finalité invoquée ou le niveau de criti"
  },
  {
    "id": "SIA-109",
    "chapterNumber": "13",
    "ruleText": "Le Groupe doit déployer et maintenir un dispositif de détection du shadow AI — usage non déclaré, non référencé et non contrôlé de SIA par des collaborateurs — couvrant au minimum : analyse des flux réseau sortants, inspection des endpoints, analyse des notes "
  },
  {
    "id": "SIA-110",
    "chapterNumber": "13",
    "ruleText": "Tout cas de shadow AI identifié doit faire l'objet d'un traitement formalisé :"
  },
  {
    "id": "SIA-111",
    "chapterNumber": "13",
    "ruleText": "Le Groupe doit offrir à ses collaborateurs des alternatives souveraines et sécurisées couvrant les principaux cas d'usage IA (rédaction, synthèse, traduction, recherche documentaire, génération de code) et s'assurer de leur accessibilité, de leur performance e"
  },
  {
    "id": "SIA-112",
    "chapterNumber": "13",
    "ruleText": "Le Groupe, lorsqu'il met à disposition un GPAI de sa propre conception à des tiers ou à ses filiales, doit respecter les obligations des fournisseurs de GPAI au sens de l'AI Act : documentation technique conforme annexe XI, information aux déployeurs en aval, "
  },
  {
    "id": "SIA-113",
    "chapterNumber": "13",
    "ruleText": "Tout GPAI à risque systémique développé, acquis ou déployé par le Groupe au sens de l'article 51 de l'AI Act doit faire l'objet des obligations renforcées : évaluation systémique, red teaming avec résultats partagés à l'AI Office le cas échéant, suivi des inci"
  },
  {
    "id": "SIA-114",
    "chapterNumber": "13",
    "ruleText": "L'usage de GPAI publics par le Groupe doit faire l'objet d'une évaluation régulière du risque agrégé : volumes transférés, catégories de données, finalités, incidents, évolutions contractuelles du fournisseur, position CNIL et régulateurs. L'évaluation aliment"
  },
  {
    "id": "SIA-115",
    "chapterNumber": "13",
    "ruleText": "Le Groupe doit informer les parties prenantes externes pertinentes — adhérents, partenaires, régulateurs, instances représentatives du personnel — de manière proportionnée, de son usage de SIA dans les processus les affectant, en respectant ses obligations de "
  },
  {
    "id": "SIA-116",
    "chapterNumber": "14",
    "ruleText": "Un dispositif de détection des incidents de sécurité spécifiques aux SIA doit être déployé et intégré au SOC du Groupe, couvrant : attaques adversariales (prompt injection, jailbreak, evasion), tentatives d'exfiltration modèle ou données, anomalies comportemen"
  },
  {
    "id": "SIA-117",
    "chapterNumber": "14",
    "ruleText": "Les incidents IA doivent être qualifiés selon une typologie en quatre niveaux : Critique (fuite massive de données adhérents, décision erronée causant préjudice significatif, prise de contrôle d'un agent, GPAI systémique compromis), Majeur (attaque réussie, dé"
  },
  {
    "id": "SIA-118",
    "chapterNumber": "14",
    "ruleText": "Les délais de notification applicables doivent être respectés pour chaque cadre réglementaire concerné : NIS2 (pré-notification < 24h à l'ANSSI, notification initiale < 72h, rapport final < 1 mois), DORA (notification ICT majeure selon règles ITS), RGPD (< 72h"
  },
  {
    "id": "SIA-119",
    "chapterNumber": "14",
    "ruleText": "out incident IA de niveau Critique ou Majeur doit déclencher l'activation de la Cellule de Crise IA (voir SIA-013) selon les délais du ch. 5, avec onvocation du RSSI, du DPO, du DSI, de la Direction Juridique, de la irection de la Communication et du propriéta"
  },
  {
    "id": "SIA-120",
    "chapterNumber": "14",
    "ruleText": "Tout SIA de tier AISVS L3, tout SIA AI Act haut risque et tout système agentique à impact personnes doit faire l'objet d'une campagne de red teaming trimestrielle, conduite par une équipe distincte des développeurs, utilisant MITRE ATLAS comme taxonomie de réf"
  },
  {
    "id": "SIA-121",
    "chapterNumber": "14",
    "ruleText": "Des exercices de purple teaming associant équipes offensives et défensives doivent être conduits au moins semestriellement sur un échantillon de SIA critiques, afin de renforcer la détection en conditions quasi-réelles et d'accélérer la capitalisation des ense"
  },
  {
    "id": "SIA-122",
    "chapterNumber": "14",
    "ruleText": "Des exercices de tabletop (simulation sur table) couvrant des scénarios de crise IA — fuite massive de données adhérents via RAG, compromission d'un agent autonome, hallucination en masse dans une communication client, détection d'un deepfake dans un processus"
  },
  {
    "id": "SIA-123",
    "chapterNumber": "14",
    "ruleText": "Tout incident Critique ou Majeur doit faire l'objet d'un post-mortem formalisé dans un délai de 15 jours ouvrés, couvrant : chronologie, causes racines, impact réel et potentiel, actions de remédiation, mesures préventives, enseignements pour le reste du porte"
  },
  {
    "id": "SIA-124",
    "chapterNumber": "14",
    "ruleText": "Le Groupe devrait participer activement aux dispositifs de partage d'information sur les menaces IA : CERT-FR, ISAC sectoriel (santé, assurance, banque), initiatives ANSSI et ENISA. Les incidents anonymisés sont partagés aux communautés pertinentes dans le res"
  },
  {
    "id": "SIA-125",
    "chapterNumber": "14",
    "ruleText": "Une base de connaissance des incidents IA et des enseignements tirés doit être tenue par le RSSI, accessible aux acteurs habilités, utilisée pour la formation continue, la mise à jour des scénarios de red teaming et l'adaptation de la politique. La base est re"
  },
  {
    "id": "SIA-126",
    "chapterNumber": "15",
    "ruleText": "Un dispositif de veille réglementaire IA doit être opérationnel, couvrant AI Act et ses actes délégués, DORA et ses RTS/ITS, NIS2 et sa transposition française, RGPD et positions CNIL, HDS, normes ETSI et CEN-CENELEC (prEN 304 223, prEN 18282), ISO 42001 et év"
  },
  {
    "id": "SIA-127",
    "chapterNumber": "15",
    "ruleText": "Le Groupe doit tenir une feuille de route de conformité AI Act publiée et tenue à jour, comportant pour chaque obligation et chaque échéance (août 2025 pour GPAI, août 2026 pour haut risque, août 2027 pour obligations complètes) : périmètre impacté, actions à "
  },
  {
    "id": "SIA-128",
    "chapterNumber": "15",
    "ruleText": "Les SIA critiques au sens DORA — supportant des fonctions métiers critiques ou importantes — doivent être intégrés au cadre de gestion des risques ICT du Groupe (registre des systèmes, testing, gestion des tiers, gestion des incidents). La classification DORA "
  },
  {
    "id": "SIA-129",
    "chapterNumber": "15",
    "ruleText": "Pour les SIA relevant du périmètre NIS2 du Groupe (entité importante ou essentielle), les obligations de gestion des risques cybersécurité (art. 21), de notification d'incident selon les délais 24h/72h/1 mois (art. 23) et de sensibilisation du management (art."
  },
  {
    "id": "SIA-130",
    "chapterNumber": "15",
    "ruleText": "Tout SIA traitant des données de santé à caractère personnel doit être hébergé sur une infrastructure certifiée HDS. L'hébergeur et ses sous- traitants doivent satisfaire les engagements HDS tout au long du cycle de vie du SIA. L'ouverture d'un SIA santé condi"
  },
  {
    "id": "SIA-131",
    "chapterNumber": "15",
    "ruleText": "Tout SIA entrant dans le registre des traitements RGPD doit y figurer avec : finalité, base légale, catégories de données, destinataires, durées de conservation, mesures de sécurité, AIPD si applicable. Le registre est tenu par le DPO et accessible à l'audit i"
  },
  {
    "id": "SIA-132",
    "chapterNumber": "15",
    "ruleText": "Le Groupe devrait se doter d'un système de management de l'IA (AIMS) conforme à ISO 42001 et engager une démarche de certification à horizon 2027, avec jalons : auto-évaluation de maturité, plan de mise en conformité, pré-audit, audit de certification. L'AIMS "
  },
  {
    "id": "SIA-133",
    "chapterNumber": "15",
    "ruleText": "Un audit externe annuel de conformité IA doit être conduit par un tiers indépendant accrédité, couvrant gouvernance, tiering, cycle de vie, supply chain, gestion des incidents, et — à partir de l'entrée en vigueur de la certification — l'AIMS ISO 42001. Le rap"
  },
  {
    "id": "SIA-134",
    "chapterNumber": "15",
    "ruleText": "Pour les SIA supportant des fonctions métiers critiques ou importantes au sens DORA, des tests de pénétration avancés (Threat Led Penetration Testing ou équivalents) doivent être conduits selon les exigences des RTS DORA, couvrant l'ensemble de la surface d'at"
  },
  {
    "id": "SIA-135",
    "chapterNumber": "15",
    "ruleText": "Le reporting réglementaire périodique aux autorités (ACPR pour DORA et Solvabilité II lorsque pertinent, CNIL pour RGPD, ANSSI pour NIS2, éventuellement AI Office pour GPAI systémique) doit être piloté par un responsable identifié, avec plan de production, rev"
  },
  {
    "id": "SIA-136",
    "chapterNumber": "16",
    "ruleText": "Un plan de formation et de sensibilisation IA-sécurité doit être établi annuellement par le RSSI en coordination avec la DRH, validé par le Comité IA, couvrant : tous les collaborateurs (sensibilisation), les utilisateurs de SIA internes, les développeurs IA, "
  },
  {
    "id": "SIA-137",
    "chapterNumber": "16",
    "ruleText": "Chaque collaborateur doit suivre, à l'embauche puis annuellement, une sensibilisation obligatoire d'au moins une heure couvrant : notions clés d'IA, risques sécurité et confidentialité, règles de la présente politique, identification du shadow AI, points de co"
  },
  {
    "id": "SIA-138",
    "chapterNumber": "16",
    "ruleText": "Les membres de la fonction sécurité (RSSI et équipe), de la fonction DPO et de la DSI directement impliqués dans les SIA doivent suivre une formation approfondie de 16 heures minimum par an, couvrant : AI Act et actes délégués, ISO 42001, ETSI prEN 304 223, pr"
  },
  {
    "id": "SIA-139",
    "chapterNumber": "16",
    "ruleText": "Les développeurs IA doivent suivre, avant tout projet et annuellement, une formation de 8 heures minimum couvrant : OWASP LLM Top 10, OWASP AISVS, OWASP GenAI Data Security, ISO 27090, pratiques de pipeline sécurisé, gestion des secrets, revue de code IA, prom"
  },
  {
    "id": "SIA-140",
    "chapterNumber": "16",
    "ruleText": "Les superviseurs humains de SIA AI Act haut risque ou AISVS L2-L3 doivent suivre une formation dédiée de 4 heures minimum par an, couvrant : rôle et responsabilités HITL, limites et modes de défaillance du SIA supervisé, interfaces et outils, procédures d'esca"
  },
  {
    "id": "SIA-141",
    "chapterNumber": "16",
    "ruleText": "Des communications régulières — newsletters, alertes internes, retours d'expérience anonymisés, points d'actualité réglementaire — doivent être diffusées par le RSSI aux populations concernées afin d'entretenir la vigilance et d'intégrer rapidement les enseign"
  },
  {
    "id": "SIA-142",
    "chapterNumber": "16",
    "ruleText": "La maturité IA-sécurité du Groupe doit être évaluée annuellement : enquêtes de connaissance, mesure des comportements (taux de shadow AI détecté, incidents évitables), évaluation du retour sur formation, benchmark CESIN. Les résultats orientent le plan de form"
  },
  {
    "id": "SIA-143",
    "chapterNumber": "17",
    "ruleText": "Le Groupe affirme la souveraineté numérique comme un critère structurant de ses choix IA, au même titre que la sécurité, la conformité et la performance. Cette position se traduit par des exigences différenciées selon la sensibilité des données et la criticité"
  },
  {
    "id": "SIA-144",
    "chapterNumber": "17",
    "ruleText": "Les SIA traitant des données classées Confidentiel ou Secret, les SIA supportant des fonctions critiques, et tout SIA traitant des données de santé adhérent doivent être hébergés sur infrastructure certifiée HDS, SecNumCloud (recommandé pour AISVS L3) ou équiv"
  },
  {
    "id": "SIA-145",
    "chapterNumber": "17",
    "ruleText": "À caractéristiques fonctionnelles et de sécurité équivalentes, les éditeurs européens et les composants issus d'initiatives de souveraineté numérique (modèles ouverts européens, cloud souverain, écosystèmes Gaia-X) devraient être privilégiés lors des choix d'a"
  },
  {
    "id": "SIA-146",
    "chapterNumber": "17",
    "ruleText": "Toute contractualisation d'un composant IA intégrant le traitement de données du Groupe doit inclure, dans les clauses contractuelles types, la clause de non-rétroaction (voir SIA-065), la clause de localisation"
  },
  {
    "id": "SIA-147",
    "chapterNumber": "17",
    "ruleText": "Le Groupe doit documenter, pour chaque SIA dépendant d'un composant critique externe (modèle propriétaire, API, infrastructure cloud), un plan de réversibilité et de substitution permettant la migration ou l'internalisation en cas de rupture, d'évolution régle"
  },
  {
    "id": "SIA-148",
    "chapterNumber": "17",
    "ruleText": "Le Groupe doit suivre l'évolution des risques extraterritoriaux affectant les composants IA qu'il utilise : Cloud Act américain, lois chinoises sur la cybersécurité, évolutions du Schrems et Data Privacy Framework, sanctions internationales. Les adaptations né"
  },
  {
    "id": "SIA-149",
    "chapterNumber": "17",
    "ruleText": "Le Groupe devrait participer à des initiatives collectives ou sectorielles renforçant la souveraineté numérique IA : Gaia-X, groupes de travail CLUSIF et CESIN, consortiums de l'écosystème santé-protection sociale, pilotes d'hébergement et de modèles souverain"
  },
  {
    "id": "SIA-150",
    "chapterNumber": "18",
    "ruleText": "Les manquements à la présente politique sont sanctionnés selon une grille graduée à quatre niveaux : Mineur (usage non intentionnel, données non sensibles), Majeur (usage de SIA public sur données internes, contournement de contrôles), Grave (exposition de don"
  },
  {
    "id": "SIA-151",
    "chapterNumber": "18",
    "ruleText": "Toute procédure disciplinaire consécutive à un manquement à la présente politique doit respecter les droits de la défense du collaborateur : information écrite des griefs, entretien préalable avec possibilité d'assistance, instruction"
  },
  {
    "id": "SIA-152",
    "chapterNumber": "18",
    "ruleText": "Les manquements à la présente politique qui constituent par ailleurs une infraction pénale (atteinte aux données, violation du secret professionnel, divulgation illégale, contrefaçon) ou une faute civile (manquement à une obligation contractuelle, préjudice à "
  },
  {
    "id": "SIA-153",
    "chapterNumber": "18",
    "ruleText": "Les cas significatifs de manquements à la présente politique, une fois traités et clos, peuvent faire l'objet d'une communication interne anonymisée à visée pédagogique, dans le respect des droits des personnes concernées. Cette communication nourrit le dispos"
  },
  {
    "id": "SIA-154",
    "chapterNumber": "19",
    "ruleText": "La présente politique doit faire l'objet d'une revue annuelle complète pilotée par le RSSI, avec contributions du DPO, de la DSI, de la Direction Juridique et des instances métier, validée en Comité des Risques. La revue examine la cohérence avec le cadre régl"
  },
  {
    "id": "SIA-155",
    "chapterNumber": "19",
    "ruleText": "Une revue d'urgence doit être déclenchée en cas d'événement majeur impactant le cadre de la politique : publication d'un texte réglementaire structurant (acte délégué AI Act, RTS DORA, directive nationale), incident critique interne ou de place, décision d'une"
  },
  {
    "id": "SIA-156",
    "chapterNumber": "19",
    "ruleText": "Un jeu d'indicateurs de performance clé doit être défini, mesuré et publié : taux de conformité des SIA à la politique, couverture Model Card / Risk Card, fréquence et qualité du red teaming, MTTD et MTTC des incidents IA, taux de détection du shadow AI, satis"
  },
  {
    "id": "SIA-157",
    "chapterNumber": "19",
    "ruleText": "Un tableau de bord de pilotage de la sécurité IA doit être maintenu, accessible aux instances de gouvernance, présentant la vision consolidée : portefeuille IA, tiers, incidents, audits, dérogations, dette technique, shadow AI, formation, conformité réglementa"
  },
  {
    "id": "SIA-158",
    "chapterNumber": "19",
    "ruleText": "Les enseignements tirés des incidents IA (ch. 14) doivent être systématiquement intégrés aux mises à jour de la politique et des procédures associées, selon un processus formalisé : analyse en post- mortem, proposition de mise à jour, validation en Comité IA, "
  },
  {
    "id": "SIA-159",
    "chapterNumber": "19",
    "ruleText": "Le Groupe devrait conduire annuellement un benchmark externe de sa posture IA-sécurité, s'appuyant sur les études CESIN, les publications CLUSIF, les retours des pairs sectoriels via les groupes de travail professionnels, les rapports d'observatoires (ANSSI, E"
  },
  {
    "id": "SIA-160",
    "chapterNumber": "19",
    "ruleText": "Toute évolution de la présente politique — mise à jour annuelle, mise à jour d'urgence, corrections ponctuelles — doit suivre un processus documenté : proposition motivée, consultation des parties prenantes (RSSI, DPO, DSI, Juridique, IRP pour les points conce"
  },
  {
    "id": "SIA-161",
    "chapterNumber": "19",
    "ruleText": "Les appels aux modèles IA — qu'ils soient internes ou consommés via API externe — doivent être authentifiés par des mécanismes robustes : clés API à haute entropie, OAuth 2.0 avec scopes restreints, ou mTLS pour les communications serveur-serveur. L'authentifi"
  },
  {
    "id": "SIA-162",
    "chapterNumber": "19",
    "ruleText": "Les secrets associés aux SIA (clés API, tokens, mots de passe techniques, certificats) doivent être gérés dans un coffre-fort centralisé avec rotation automatique périodique : 90 jours maximum pour les clés API, 30 jours pour les tokens d'accès long-lived, à e"
  },
  {
    "id": "SIA-163",
    "chapterNumber": "19",
    "ruleText": "Les outils exposés aux agents (voir ch. 10) doivent être protégés par un RBAC granulaire au niveau de chaque action : un agent ne peut invoquer un outil que si la permission correspondante est explicitement accordée dans son profil, avec contrôle à chaque appe"
  },
  {
    "id": "SIA-164",
    "chapterNumber": "19",
    "ruleText": "Les manifests MCP décrivant les outils et leurs scopes doivent être signés cryptographiquement par l'émetteur avec un algorithme au moins équivalent à Ed25519, la signature étant vérifiée avant toute utilisation. Les manifests non signés ou à signature invalid"
  },
  {
    "id": "SIA-165",
    "chapterNumber": "19",
    "ruleText": "Seuls les serveurs MCP figurant explicitement sur une allowlist approuvée peuvent être utilisés par les agents du Groupe. La liste est tenue par le RSSI, révisée trimestriellement, et comporte pour chaque serveur : finalité, propriétaire, scopes autorisés, dat"
  },
  {
    "id": "SIA-166",
    "chapterNumber": "19",
    "ruleText": "Les scopes déclarés par les serveurs MCP doivent être minimaux et explicites : pas de scope agrégé (read_everything, admin_full), décomposition par ressource et par action. Les scopes excessifs font l'objet"
  },
  {
    "id": "SIA-167",
    "chapterNumber": "19",
    "ruleText": "Lorsque l'entraînement ou l'évaluation d'un SIA implique des datasets à forte sensibilité (santé, financier adhérent) et que l'anonymisation pleine n'est pas possible sans perte d'utilité, la confidentialité différentielle doit être appliquée avec un paramètre"
  },
  {
    "id": "SIA-168",
    "chapterNumber": "19",
    "ruleText": "Lorsque la mutualisation de données entre entités nécessite un entraînement IA mais sans transfert effectif des données, la technique du federated learning devrait être évaluée comme alternative au transfert centralisé, avec analyse de risques spécifique (fuit"
  },
  {
    "id": "SIA-169",
    "chapterNumber": "19",
    "ruleText": "Pour les cas d'usage critiques où le modèle doit inférer sur des données que le fournisseur du modèle ne doit pas voir (par exemple calcul actuariel partagé), l'homomorphic encryption devrait être évaluée. Son coût computationnel et ses limitations fonctionnel"
  },
  {
    "id": "SIA-170",
    "chapterNumber": "19",
    "ruleText": "Le secure multi-party computation devrait être évalué pour les calculs IA collaboratifs entre entités concurrentes ou mutuellement défiantes (par exemple benchmark sectoriel, calcul de risques agrégés) où les données ne peuvent être centralisées. La maturité d"
  },
  {
    "id": "SIA-171",
    "chapterNumber": "19",
    "ruleText": "Les modèles propriétaires du Groupe présentant une valeur significative en propriété intellectuelle ou une sensibilité particulière devraient intégrer un dispositif de watermarking robuste, permettant la détection d'une exfiltration par interrogation massive o"
  },
  {
    "id": "SIA-172",
    "chapterNumber": "19",
    "ruleText": "Les datasets sensibles utilisés en entraînement devraient intégrer des canary tokens — enregistrements synthétiques uniques conçus pour détecter une fuite — dont la présence dans des sorties de modèles ou dans des fuites externes constitue un indicateur d'inci"
  }
];
const PSSI_CHAPTERS: PssiChapterIndex[] = [
  {
    "number": "2",
    "title": "Champ d'application, périmètre et exclusions",
    "count": 3
  },
  {
    "number": "5",
    "title": "Gouvernance, organisation et RACI",
    "count": 10
  },
  {
    "number": "6",
    "title": "Tiering des SIA — matrice AI Act × AISVS",
    "count": 7
  },
  {
    "number": "7",
    "title": "Exigences de sécurité par phase du cycle de vie",
    "count": 28
  },
  {
    "number": "8",
    "title": "Gestion des données pour les SIA",
    "count": 13
  },
  {
    "number": "9",
    "title": "Supply chain, AI-BOM et intégrité",
    "count": 12
  },
  {
    "number": "10",
    "title": "Systèmes agentiques",
    "count": 12
  },
  {
    "number": "11",
    "title": "Génération de code source assistée par IA",
    "count": 10
  },
  {
    "number": "12",
    "title": "Supervision humaine et accountability",
    "count": 8
  },
  {
    "number": "13",
    "title": "GPAI publics, transparence et shadow AI",
    "count": 12
  },
  {
    "number": "14",
    "title": "Détection, incident response et red teaming",
    "count": 10
  },
  {
    "number": "15",
    "title": "Conformité réglementaire",
    "count": 10
  },
  {
    "number": "16",
    "title": "Formation et sensibilisation",
    "count": 7
  },
  {
    "number": "17",
    "title": "Souveraineté numérique et maîtrise des tiers",
    "count": 7
  },
  {
    "number": "18",
    "title": "Sanctions et mesures disciplinaires",
    "count": 4
  },
  {
    "number": "19",
    "title": "Processus de revue et d'amélioration continue",
    "count": 19
  }
];
const PSSI_VERSION = "3.0";
const PSSI_TOTAL_RULES = 172;
// <PSSI_SUMMARY_END>

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(204).end();

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { message, mode, llmConfig } = req.body || {};

    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    const geminiApiKey = process.env.GEMINI_API_KEY;

    if (!geminiApiKey) {
      return res.status(200).json({
        sessionId: `session-${Date.now()}`,
        answer: generateFallbackResponse(message),
        reasoning: [],
        toolsUsed: [],
        mode: 'fallback',
      });
    }

    // Call Gemini API
    const geminiResponse = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=${geminiApiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: buildSystemPrompt(mode) + '\n\nQuestion utilisateur: ' + message,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: llmConfig?.temperature ?? 0.7,
            maxOutputTokens: llmConfig?.maxTokens ?? 2048,
          },
        }),
      }
    );

    if (!geminiResponse.ok) {
      const errText = await geminiResponse.text();
      console.error('Gemini API error:', errText);
      // Distinguish rate limit from other errors
      const isRateLimit = geminiResponse.status === 429;
      const answer = isRateLimit
        ? "Le quota API Gemini est temporairement epuise. Veuillez reessayer dans quelques instants. En attendant, voici une reponse locale:\n\n" + generateFallbackResponse(message)
        : generateFallbackResponse(message);
      return res.status(200).json({
        sessionId: `session-${Date.now()}`,
        answer,
        reasoning: [],
        toolsUsed: [],
        mode: isRateLimit ? 'rate-limited' : 'fallback',
      });
    }

    const geminiData: any = await geminiResponse.json();
    const answer =
      geminiData.candidates?.[0]?.content?.parts?.[0]?.text ||
      generateFallbackResponse(message);

    res.status(200).json({
      sessionId: `session-${Date.now()}`,
      answer,
      reasoning: [
        {
          step: 1,
          thought: 'Analyse de la question utilisateur',
          action: 'Gemini 3 Flash Preview',
          result: 'Reponse generee',
        },
      ],
      toolsUsed: ['gemini-3-flash-preview'],
      mode: 'gemini',
    });
  } catch (error: any) {
    console.error('Chatbot error:', error);
    res.status(200).json({
      sessionId: `session-${Date.now()}`,
      answer: generateFallbackResponse(req.body?.message || ''),
      reasoning: [],
      toolsUsed: [],
      mode: 'fallback',
      error: error.message,
    });
  }
}

function buildSystemPrompt(mode?: string): string {
  const dsgaiList = DSGAI_SUMMARY
    .map((i) => `  ${i.code} — ${i.title}${i.priority ? ` [${i.priority}]` : ''}`)
    .join('\n');

  const pssiChapterList = PSSI_CHAPTERS
    .map((c) => `  Ch.${c.number} — ${c.title} (${c.count} SIA)`)
    .join('\n');

  return `Tu es un assistant expert en securite IA et red teaming. Tu assistes les utilisateurs de la plateforme AI Risk Manager.

Domaines d'expertise:
- OWASP LLM Top 10 et Top 15 Agentic AI
- Tests de securite LLM (Garak, Promptfoo)
- Gouvernance et politiques IA
- Red teaming et audit de securite
- Gestion des risques IA (taxonomie causale et par domaine)
- OWASP GenAI COMPASS (31 scenarios)
- OWASP GenAI Data Security 2026 — 22 risques (DSPM + DSGAI01..DSGAI21)
- PSSI IA v${PSSI_VERSION} — Politique de Securite des Systemes d'IA (${PSSI_TOTAL_RULES} exigences SIA-001..SIA-172)

Liste des 22 risques DSGAI disponibles (avec priorite) :
${dsgaiList}

Chapitres de la PSSI IA v${PSSI_VERSION} (${PSSI_TOTAL_RULES} exigences reparties) :
${pssiChapterList}

Referentiels sources de la PSSI IA v${PSSI_VERSION} : AI Act, RGPD, DORA, NIS2, ISO 42001, ISO 27001, ISO 27090, OWASP AISVS, OWASP LLM Top 10, OWASP Agentic, OWASP GenAI Data Security 2026, MITRE ATLAS, NIST AI RMF, CLUSIF, CESIN, ANSSI.

Si l'utilisateur mentionne un identifiant SIA-XXX (ex: SIA-042), consulte la liste PSSI_SUMMARY pour retrouver l'exigence et son chapitre. Pour un detail approfondi (texte complet de la regle, tier applicable, RACI, frequence de revue, referentiels cites, controle testable), invite l'utilisateur a ouvrir Gouvernance IA > Politique IA (SIA).

Si l'utilisateur mentionne un code DSGAI (ex: DSGAI05) ou pose une question sur la securite des donnees GenAI, reponds en t'appuyant sur la liste DSGAI. Pour un detail approfondi d'un risque specifique (attack vectors, mitigations tier 1/2/3), invite l'utilisateur a consulter le Wiki Red Teamer > section "Securite Donnees GenAI (DSGAI)".

Reponds en francais. Sois precis et actionnable.${mode === 'concise' ? ' Sois bref et direct.' : ''}${mode === 'expert' ? ' Donne des details techniques approfondis.' : ''}`;
}

function generateFallbackResponse(message: string): string {
  const lower = message.toLowerCase();

  // PSSI IA v3 identifiers (SIA-001..SIA-172) — highest priority match
  const siaMatch = message.match(/\bSIA-?(\d{1,3})\b/i);
  if (siaMatch) {
    const num = parseInt(siaMatch[1], 10);
    if (num >= 1 && num <= PSSI_TOTAL_RULES) {
      const id = 'SIA-' + String(num).padStart(3, '0');
      const item = PSSI_SUMMARY.find((i) => i.id === id);
      if (item) {
        const chapter = PSSI_CHAPTERS.find((c) => c.number === item.chapterNumber);
        const chapterLabel = chapter ? `Chapitre ${chapter.number} — ${chapter.title}` : `Chapitre ${item.chapterNumber}`;
        return `**${item.id}** (PSSI IA v${PSSI_VERSION}, ${chapterLabel})\n\n${item.ruleText}\n\nPour le texte integral, le tier applicable, le RACI et les referentiels cites, consultez Gouvernance IA > Politique IA (SIA).`;
      }
    }
    return `L'identifiant ${siaMatch[0]} n'est pas reconnu dans la PSSI IA v${PSSI_VERSION}. Identifiants valides : SIA-001 a SIA-${String(PSSI_TOTAL_RULES).padStart(3, '0')}.`;
  }

  // DSGAI codes (DSPM, DSGAI01-21)
  const dsgaiMatch = message.match(/\b(DSGAI\d{2}|DSPM)\b/i);
  if (dsgaiMatch) {
    const code = dsgaiMatch[1].toUpperCase();
    const item = DSGAI_SUMMARY.find((i) => i.code.toUpperCase() === code);
    if (item) {
      return `**${item.code} — ${item.title}** ${item.priority ? `(priorite: ${item.priority})` : ''}\n\n${item.overview}\n\nConsultez le Wiki Red Teamer > section "Securite Donnees GenAI (DSGAI)" pour les attack vectors, scenarios et mitigations tier 1/2/3.`;
    }
    return `Le code ${code} n'est pas reconnu dans le referentiel OWASP GenAI Data Security 2026. Codes valides : DSPM, DSGAI01 a DSGAI21.`;
  }

  if (lower.includes('pssi') || lower.includes('sia ') || (lower.includes('politique') && lower.includes('ia'))) {
    return `La PSSI IA v${PSSI_VERSION} consolidee couvre ${PSSI_TOTAL_RULES} exigences (SIA-001 a SIA-${String(PSSI_TOTAL_RULES).padStart(3, '0')}) reparties sur ${PSSI_CHAPTERS.length} chapitres : gouvernance, tiering AI Act x AISVS, cycle de vie (7 phases), donnees, supply chain, agentique, code assiste, supervision humaine, GPAI publics, incidents, conformite, formation, souverainete, sanctions, amelioration continue. Consultez Gouvernance IA > Politique IA (SIA) pour le detail des exigences.`;
  }

  if (lower.includes('data security') || lower.includes('securite des donnees') || lower.includes('dsgai')) {
    return "Le referentiel OWASP GenAI Data Security 2026 couvre 22 risques (DSPM + DSGAI01 a DSGAI21) : data leakage, poisoning, shadow AI, RAG, vector stores, telemetry, inference. Consultez Referentiels > Wiki Red Teamer > Securite Donnees GenAI (DSGAI) ou la banniere OWASP dans Referentiels > OWASP COMPASS.";
  }

  if (lower.includes('compass') || lower.includes('owasp')) {
    return "Le module COMPASS propose 31 scenarios de menaces bases sur le framework OWASP LLM Top 10. Consultez la section Referentiels > COMPASS pour une analyse detaillee. Referentiels OWASP integres : Top 10 LLM, Top 15 Agentic AI, COMPASS, Data Security 2026 (DSGAI).";
  }
  if (lower.includes('risque') || lower.includes('risk')) {
    return "La base de risques IA contient 1579 entrees classees par domaine, entite et intentionnalite. Explorez la section Referentiels > Base de Risques IA. Voir aussi Referentiels > COMPASS (31 scenarios) et les 22 risques OWASP Data Security 2026 (DSGAI01-21).";
  }
  if (lower.includes('garak') || lower.includes('promptfoo')) {
    return "Les outils de pentest (Garak, Promptfoo) sont disponibles via la Plateforme Unifiee. Garak scanne les vulnerabilites LLM (OWASP Top 10), Promptfoo teste les prompts avec des evaluations automatisees.";
  }
  if (lower.includes('politique') || lower.includes('policy')) {
    return `Les politiques IA sont gerees dans le module Gouvernance IA > Politique IA (SIA). La PSSI IA v${PSSI_VERSION} consolidee contient ${PSSI_TOTAL_RULES} exigences reparties sur ${PSSI_CHAPTERS.length} chapitres. Mentionnez un identifiant (ex: SIA-042) pour consulter une exigence specifique.`;
  }

  return `Je suis l'assistant AI Risk Manager. Je peux vous aider sur la securite IA (OWASP LLM Top 10, Agentic Top 15, COMPASS, Data Security 2026/DSGAI, PSSI IA v${PSSI_VERSION} — ${PSSI_TOTAL_RULES} exigences SIA), le red teaming, les tests LLM (Garak/Promptfoo), la gouvernance et les referentiels OWASP. Que souhaitez-vous savoir?`;
}
