// Re-export bridge.
//
// Historically this module shipped 22 hand-written SIA rules built on CLUSIF
// PSSI IA v1/v2. The PSSI IA v3 consolidation (172 SIA, 2026) replaces this
// dataset entirely. The legacy content is preserved verbatim in
// `aiPolicyContentLegacyV2.ts` for reference and comparison, but is no
// longer rendered in the UI.
//
// All import sites that used `CLUSIF_AI_POLICY` / `INITIAL_AI_POLICY`
// continue to work — they now resolve to the v3 dataset generated by
// scripts/generate-pssi-v3-artifacts.cjs.

export { PSSI_IA_V3_POLICY as CLUSIF_AI_POLICY } from './pssiIaV3.generated';
export { PSSI_IA_V3_POLICY as INITIAL_AI_POLICY } from './pssiIaV3.generated';
export { PSSI_IA_V3_VERSION, PSSI_IA_V3_TOTAL_RULES } from './pssiIaV3.generated';
